### ISSUE TITLE
Buildings on the rocks

### ISSUE THREAD

**Issue by Pacoofficial** [Facepunch/rust-issues#23]
Please disable build a building on the rocks, it's not fair, because they can not raid. (most commonly)
For example, I do not see any reason to play without the possibility of raid, because it is part of the gameplay. But the raid buildings that stand on the rocks - it is impossible. It's not fair!

**Comment by y0himba** [comment]
My opinion is do not disable it.  It is possible to raid a house on a rock, one just needs to work at it and prepare.  Also, raiding is not the sole purpose of the game, it is a tool added to aid in survival. Building on a rock, or in the water etc. are all ways to make a defensible home, and should be allowed. 

I would be more worried about building in caves,  The only way to damage a cave structure is with C4 currently due to the hit boxes being in weird positions. I love caves, but it feels a bit glitchy to build in them...

**Comment by thebadaids** [comment]
Given that tool cupboards are planned to change so they don't prevent you from building near then, this is a non-issue. And rock bases ARE raidable.

**Comment by SannyOK** [comment]
Paco If you can't, thats not all can't to do this, as I have already said on VK. ;)

**Comment by funjoker** [comment]
You are able to raid rock building. Did it already. Even water houses are able to get raid
