### ISSUE TITLE
Foundation LODs are still broken

### ISSUE THREAD

**Issue by garrynewman** [Facepunch/rust-issues#53]
See:

http://files.facepunch.com/garry/2015/March/23/2015-03-23_21-39-37.mp4

Conditional models should be complementary, rather than defining the block completely as they don't show up at certain distances.

**Comment by paroxum** [comment]
The core needs to be displayed 100% of the time. Will fix for this week's update.

**Comment by paroxum** [comment]
Although I must say that I do not like the idea of culling the conditional pieces this quick. Our rooftop blocks are almost solely made of CMs.. Which means people will see through homes all the time..

**Comment by garrynewman** [comment]
We really should be able to turn conditional models off completely and stuff should look normal. Maybe we need a system in which we define some of the conditional models as "default" so that if CMs aren't being used, it always shows?

**Comment by paroxum** [comment]
That's kind of what I did before by keeping a core mesh for the foundation pieces (just so happens this one has messed up over iterations :P). It should be possible to do that for rooftop blocks too, but the popping will as always be big since the volume/silhouette loss is quite a lot. We will do that for now I guess. It might be good for these blocks to use a lod fade transition if we create such popping imo

**Comment by garrynewman** [comment]
It seems like with roof blocks they should by default always have the edges? Because they're only ever really going to be visible from the outside anyway?

 I don't have much faith in the LOD fade transitions

**Comment by paroxum** [comment]
yeah rooftop core distance mesh is easy to make. I guess I'm just sad to see all that clipping happen :D

**Comment by garrynewman** [comment]
I think the transition will be a lot less obvious once whole walls don't disappear :0

**Comment by paroxum** [comment]
The foundations problem it is now fixed from CL6810 in my branch
