### ISSUE TITLE
Terrain memory optimizations

### ISSUE THREAD

**Issue by garrynewman** [Facepunch/rust-issues#56]
I've been checking out memory usage..

```
[3/24/2015 8:10:29 AM] TerrainBiomeMap allocated: 128.00mb
[3/24/2015 8:10:29 AM] TerrainColorMap allocated: 32.00mb
[3/24/2015 8:10:29 AM] TerrainHeightMap allocated: 32.03mb
[3/24/2015 8:10:29 AM] TerrainNormalMap allocated: 96.00mb
[3/24/2015 8:10:29 AM] TerrainSplatMap allocated: 288.00mb
[3/24/2015 8:10:29 AM] TerrainTopologyMap allocated: 32.00mb
```

Is there any optimizations to be made to these guys? I noticed they allocate two buffers - are they always needed? Can we clean them up at some point when they're no longer needed? Is the resolution of each of the maps important.. could we halve/quarter it without any bad effects? Could/Do we free any of them once the map is set up?

Any savings on memory we can make are a big deal, not only on the client - but on the server too where some hosts limit servers to 2gb.

**Comment by andererandre** [comment]
They don't allocate two buffers - src and dst point to the same chunk of heap memory, and only temporarily differ if certain types of processing are applied (which is always cleaned up afterwards).

* The resolutions are already pretty coarse (one value every 2 world units).
* TerrainColorMap is removed on procgen7 and replaced by TerrainBiomeMap / TerrainAlphaMap (1 float).
* We could deallocate TerrainNormalMap and calculate normals from the height values. It will slow down stuff like grass patch generation and dynamic decor spawning however.
* We could decode the texture values on the fly instead of storing full floats (slower but could make sense for TerrainSplatMap and TerrainBiomeMap, which seem to be the hardest hitters memory-wise).

Are those numbers from 6k terrains? On 4k worlds TerrainSplatMap should use 2048 * 2048 * 8 (# splats) * 4 (# bytes per float) = 134MB. Same goes for TerrainNormalMap, which should be 2048 * 2048 * 3 (# floats per vector) * 4 (# bytes per float) = 50MB, and the other ones.

**Comment by garrynewman** [comment]
Alright, sounds good.

The values I worked out probably aren't right then, I assumed they were separate buffers, so we can probably halve all those numbers?

```
src = dst = new float[res, res, num];

LogSize( this, (ulong) (sizeof( float ) * res * res * num * 2) );
```

So we're probably at around 304mb right now for a 4k terrain? What does the terrain use in terms of textures, on the client and on the server?

I'm trying to figure out where all our memory is going.

**Comment by andererandre** [comment]
Seems like all values should be halved then, yeah. All backing stores are constantly evaluated at runtime, which is the reason we've been storing them completely uncompressed up until now. The only compression that could really make sense would be to replace some floats with bytes, since that would only mean 1 additional multiplication per read and quarter the required memory. We might also be able to live without the splat values on the server if we guarantee to always use the binary topology values for static spawns that have to be done on the server, but right now we're not enforcing that. Overall backing store memory should be:
* TerrainBiomeMap: 67MB (could be packed into 1 byte per value instead of 1 float per value)
* TerrainAlphaMap: 16MB (could be packed into 1 byte per value instead of 1 float per value)
* TerrainHeightMap: 16MB (no optimizations possible, always required in RAM)
* TerrainNormalMap: 50MB (could be removed and extracted from the height map or packed into 3 bytes instead of 3 floats per value - decoding should be the faster option of the two)
* TerrainSplatMap: 134MB (could be packed into 8 bytes instead of 8 floats, would make the most sense out of all the optimziations)
* TerrainTopologyMap: 16MB (already super compressed as bitmask, currently uses 19 out of its 32 bits per value)

Not all of the fields are converted to textures, but any textures I do generate are cleared from RAM once they've been uploaded to VRAM - so assuming that functionality works the textures themselves shouldn't use any RAM at runtime. I'm calling [`Texture2D.Apply(true, true)`](http://docs.unity3d.com/ScriptReference/Texture2D.Apply.html).

**Comment by andererandre** [comment]
First round of optimizations will go live with the next wiping update:

* TerrainBiomeMap: 16MB
* TerrainAlphaMap: 4MB
* TerrainHeightMap: 16MB
* TerrainNormalMap: 48MB
* TerrainSplatMap: 32MB
* TerrainTopologyMap: 16MB

Left out TerrainNormalMap for now since that would require at least 3 multiplications per read to unpack. I'll have to confirm whether or not that's going to affect grass and dynamic decor spawning in a noticeable way and compare it to the option of calculating normals from the height map on the fly and scrap the normal map backing field altogether after the the texture has been generated and uploaded to VRAM.

**Comment by andererandre** [comment]
Did some benchmarks and decided to remove TerrainNormalMap altogether and calculate normals from height on the fly. This brings down the overall memory used by the terrain backing fields to 84MB with little to no room for further optimizations without noticeable loss of quality, so I'll close this issue for now.
